version: '3'
services:

  # PostgreSQL
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: krya
      POSTGRES_PASSWORD: krya
    ports:
      - "5432:5432"

  # Keycloak
  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
#      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: krya
      DB_PASSWORD: krya
    ports:
      - "8081:8080"
    depends_on:
      - postgres
