spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/miniprojectjpa
    username: postgres
    password: krya

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/krya
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 100KB
  mail:
    host: smtp.gmail.com
    port: 587
    username: vannkrya069@gmail.com
    password: glkootfsgzphxjrz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#hibernate:
#  jdbc:
logging:
  level:
    com.levi.testhibernate: debug
#    batch_size: 1
storeFile : "http://localhost:8088/images/"

server:
  port: 8088



